"""initial schema

Revision ID: 75645914ca0a
Revises: 
Create Date: 2026-09-08 17:07:02.332602
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_key'), 'company_settings', ['key'], unique=True)
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_type', sa.String(length=50), server_default='Raw Material Vendor', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_contacts_contact_name'), 'contacts', ['contact_name'], unique=False)
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=30), server_default='FG', nullable=False),
    sa.Column('remarks', sa.String(length=150), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_code', name='uq_item_code')
    )
    op.create_index(op.f('ix_items_item_code'), 'items', ['item_code'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('vendor_process_types',
    sa.Column('process_type_id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('process_type_id'),
    sa.UniqueConstraint('process_type', name='uq_vendor_process_type')
    )
    op.create_index(op.f('ix_vendor_process_types_process_type'), 'vendor_process_types', ['process_type'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendors_vendor_name'), 'vendors', ['vendor_name'], unique=False)
    op.create_table('job_work_issues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('issue_no', sa.String(length=30), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_job_work_issues_issue_no'), 'job_work_issues', ['issue_no'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('stock_ledger',
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('reference_no', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_in', sa.Integer(), nullable=False),
    sa.Column('qty_out', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('ledger_id')
    )
    op.create_index(op.f('ix_stock_ledger_item_id'), 'stock_ledger', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_reference_no'), 'stock_ledger', ['reference_no'], unique=False)
    op.create_index(op.f('ix_stock_ledger_transaction_type'), 'stock_ledger', ['transaction_type'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('grns',
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=30), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('grn_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.PrimaryKeyConstraint('grn_id')
    )
    op.create_index(op.f('ix_grns_grn_number'), 'grns', ['grn_number'], unique=True)
    op.create_table('job_work_issue_items',
    sa.Column('issue_item_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('issued_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['job_work_issues.issue_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('issue_item_id')
    )
    op.create_table('job_work_receipts',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=30), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['job_work_issues.issue_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_index(op.f('ix_job_work_receipts_receipt_no'), 'job_work_receipts', ['receipt_no'], unique=True)
    op.create_table('purchase_order_items',
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('stock_out_item_id', sa.Integer(), nullable=True),
    sa.Column('target_fg_item_id', sa.Integer(), nullable=True),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['stock_out_item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['target_fg_item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('po_item_id')
    )
    op.create_table('user_identities',
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_identity')
    )
    op.create_index(op.f('ix_user_identities_provider'), 'user_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_user_identities_provider_user_id'), 'user_identities', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('grn_items',
    sa.Column('grn_item_id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('damaged_qty', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.grn_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('grn_item_id')
    )
    op.create_table('job_work_receipt_items',
    sa.Column('receipt_item_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('rejected_qty', sa.Integer(), nullable=False),
    sa.Column('process_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['job_work_receipts.receipt_id'], ),
    sa.PrimaryKeyConstraint('receipt_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_work_receipt_items')
    op.drop_table('grn_items')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_provider_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_provider'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_job_work_receipts_receipt_no'), table_name='job_work_receipts')
    op.drop_table('job_work_receipts')
    op.drop_table('job_work_issue_items')
    op.drop_index(op.f('ix_grns_grn_number'), table_name='grns')
    op.drop_table('grns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_ledger_transaction_type'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_reference_no'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_item_id'), table_name='stock_ledger')
    op.drop_table('stock_ledger')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_job_work_issues_issue_no'), table_name='job_work_issues')
    op.drop_table('job_work_issues')
    op.drop_index(op.f('ix_vendors_vendor_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_vendor_process_types_process_type'), table_name='vendor_process_types')
    op.drop_table('vendor_process_types')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_item_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_name'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_settings_key'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
